// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Echo echo
//
// swagger:model Echo
type Echo struct {

	// message
	// Max Length: 30
	Message string `json:"Message,omitempty"`
}

// Validate validates this echo
func (m *Echo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Echo) validateMessage(formats strfmt.Registry) error {
	if swag.IsZero(m.Message) { // not required
		return nil
	}

	if err := validate.MaxLength("Message", "body", m.Message, 30); err != nil {
		return err
	}

	// Validate MaxBytes Length
	if len([]byte(m.Message)) > 30 {
		return errors.TooLong("Message", "body", 30, m.Message)
	}

	return nil
}

// ContextValidate validates this echo based on context it is used
func (m *Echo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Echo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Echo) UnmarshalBinary(b []byte) error {
	var res Echo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
